version: '3.8'

services:
  # MongoDB服務
  mongo:
    image: mongo:latest
    container_name: mern-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  # 後端API服務
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: mern-server
    restart: always
    expose:
      - "5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/mern-todo-app
      - JWT_SECRET=your_jwt_secret_key_change_this_in_production
      - PORT=5000
      - CLIENT_URL=http://localhost:80
    networks:
      - mern-network

  # 前端React應用
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: mern-client
    restart: always
    expose:
      - "3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://nginx/api
    networks:
      - mern-network

  # 新增：Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: mern-nginx
    restart: always
    ports:
      - "80:80"  # HTTP端口
      - "443:443" # HTTPS端口（如果需要SSL）
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl  # SSL證書目錄（如果需要SSL）
    depends_on:
      - client
      - server
    networks:
      - mern-network

# 定義卷和網絡
volumes:
  mongo-data:

networks:
  mern-network:
    driver: bridge 